name: hamsm_env
channels:
  - conda-forge
  - defaults
dependencies:
 - numpy<1.24
 - networkx
 - h5py
 - matplotlib
 - mdtraj
 - pyemma
 - sphinx_rtd_theme
 - flake8
 - Sphinx
 - pytest
 - rich
 - sphinx_rtd_theme
 - tqdm
 - scipy
 - westpa
 - nbsphinx
 - mdanalysis
 - deeptime
 - pip
 - pip:
   - ray
   - synd
   - .
variables:
  OMP_NUM_THREADS: 1
  RAY_worker_register_timeout_seconds: 60
