name: hamsm_env
channels:
  - conda-forge
  - defaults
dependencies:
 - numpy
 - networkx
 - h5py<3.2
 - matplotlib
 - mdtraj
 - pyemma
 - sphinx_rtd_theme
 - flake8
 - Sphinx
 - pytest
 - rich
 - sphinx_rtd_theme
 - tqdm
 - scipy
 - pip
 - pip:
   - ray
   - .
